config/routes.rb
Rails.application.routes.draw do
  resources :cars
  root 'cars#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id                      :integer          not null, primary key
#  manufacturer            :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
class Car < ApplicationRecord
    # Each car (manufacturer) has many variants (model, year, color)
    has_many :variants
    accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true
end

app/models/variant.rb
# == Schema Information
#
# Table name: variants
#
#  id                      :integer          not null, primary key
#  car_id                  :integer          not null, foreign key
#  model                   :string
#  year                    :datetime
#  color                   :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
class Variant < ApplicationRecord
  # Each variant belongs to a car (manufacturer). Referenced via foreign key
  belongs_to :car
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    @cars = Car.all
  end

  def update
    if car.update(car_params)
      redirect_to cars_path
    else
      render :edit
    end
  end

  private

  def car_params
    params
      .require(:car)
       .permit(
         variants_attributes: [:_destroy, :id, :model]
       )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Manufacturer:</strong>
    <%= car.manufacturer %>
  </p>

</div>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/index.html.erb
<br>
<br>
<div data-controller="hello">
  <input data-hello-target="name" type="text">
  <button data-action="click->hello#greet">Greet</button>
</div>
<br>


<div data-controller="toggle" data-toggle-show-class="show">
  <button class="btn" data-action="toggle#show">Toggle</button>
  <div class="hide" data-toggle-target="text">You toggled me!</div>
</div>
<br>

<div data-controller="toggle" data-toggle-hide-class="hide" data-toggle-show-class="show">
  <button class="show" data-action="toggle#switch" data-toggle-target="one">One</button>
  <div>Up and down</div>
  <button class="hide" data-action="toggle#switch" data-toggle-target="two">And two</btn>
</div>

<br>
<div class="box" data-controller="toggle" data-toggle-highlight-class="highlight" data-toggle-target="checkbox">
  <input type="checkbox" data-action="toggle#highlight">
</div>

<br>
<div class="box" data-controller="textwarn" data-textwarn-red-class="red">
  <textarea maxlength="280" type="textarea" data-action="textwarn#warn" data-textwarn-target="text"></textarea>
  <p class="" data-textwarn-target="length">0/280 characters</p>
</div>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path %>
</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div>
  <%= link_to "Edit this car", edit_car_path(@car) %> |
  <%= link_to "Back to cars", cars_path %>

  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>